version: 2

#sources: These are the source system tables which are directly used in the ETL processes.
sources:
  - name: raw
    tables:
      - name: conversions
      - name: sessions
        tests:
          - unique:
              column_name: "(userid||'-'||time_started||'-'||medium)"
              

models:
  - name: staging_all_sessions
    description: Staging all sessions from different channels
    columns:
      - name: session_sk
        description: The surrogate key for the all_sessions table
        tests:
          - unique
          - not_null

